application: open-waffle
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /include/css
  static_dir: include/css
  
- url: /include/img
  static_dir: include/img

- url: /.*
  script: index.php  
